$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 2
shell_integration: true
patch_pwsh_bleed: true
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: os
        style: plain
        template: "{{ if .WSL }}WSL at {{ end }}{{.Icon}} "
        background: ""
        foreground: p:os
        Text: ""
        Duration: 0
        NameLength: 0
      - type: session
        style: plain
        template: " {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} "
        background: ""
        foreground: p:blue
        Text: ""
        Duration: 0
        NameLength: 0
      - type: path
        style: plain
        template: " {{ .Path }} "
        properties:
          folder_icon: ....
          home_icon: "~"
          style: agnoster_short
        background: ""
        foreground: p:cyan
        Text: ""
        Duration: 0
        NameLength: 0
      - type: git
        style: plain
        template: " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if
          .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and
          (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if
          .Staging.Changed }}  {{ .Staging.String }}{{ end }} "
        properties:
          branch_icon: " "
          cherry_pick_icon: " "
          commit_icon: " "
          fetch_status: false
          fetch_upstream_icon: false
          merge_icon: " "
          no_commits_icon: " "
          rebase_icon: " "
          revert_icon: " "
          tag_icon: " "
        background: ""
        foreground: p:lavender
        Text: ""
        Duration: 0
        NameLength: 0
  - type: prompt
    alignment: right
    filler: <p:os>.
    segments:
      - foreground: p:lavender
        properties:
          fetch_package_manager: true
          npm_icon: " <p:red></p:red> "
          yarn_icon: " <p:blue></p:blue>"
        style: plain
        template: "  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{
          .Full }} "
        type: node
      - foreground: p:yellow
        style: plain
        template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{
          end }}{{ .Full }}{{ end }} "
        type: python
      - foreground: p:blue
        style: plain
        template: " 󰟓 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
        type: go
      - foreground: p:brightBlue
        style: plain
        template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
        type: azfunc
      - foreground: p:brightYellow
        style: plain
        template: " 󰸏 {{.Profile}}{{if .Region}}@{{.Region}}{{end}} "
        type: aws
      - foreground: p:blue
        style: plain
        template: " 󱃾 {{.Context}}{{if .Namespace}} @ {{.Namespace}}{{end}} "
        type: kubectl
      - background: ""
        foreground: p:cyan
        properties:
          time_format: 15:04
        style: plain
        template: " {{ .CurrentDate | date .Format }} "
        type: time
      - type: command
        style: plain
        template: " {{ if eq .Code 0 }} {{- .Output }} {{ end }} "
        foreground: "p:pink"
        properties:
          shell: "sh"
          command: 'mommy -1 -s  0 | cat'
      - type: command
        style: plain
        template: " {{ if gt .Code 0 }} {{- .Output }} {{ end }} "
        foreground: "p:red"
        properties:
          shell: "sh"
          command: 'mommy -1 -s  1 | cat'
  - type: prompt
    alignment: left
    segments:
      - type: shell
        style: plain
        template: "{{.Name}}  "
        foreground: p:lavender
      - type: text
        style: plain
        background: ""
        foreground: p:pink
        template: "{{ if .Root }}#>{{ else }}~>{{end}} "
        Duration: 0
        NameLength: 0
    newline: true
palette:
  background: "#24273A"
  black: "#494D64"
  blue: "#8AADF4"
  brightBlack: "#5B6078"
  brightBlue: "#8AADF4"
  brightCyan: "#8BD5CA"
  brightGreen: "#A6DA95"
  brightPurple: "#F5BDE6"
  brightRed: "#ED8796"
  brightWhite: "#A5ADCB"
  brightYellow: "#EED49F"
  cursorColor: "#F4DBD6"
  cyan: "#8BD5CA"
  foreground: "#CAD3F5"
  green: "#A6DA95"
  purple: "#F5BDE6"
  red: "#ED8796"
  selectionBackground: "#5B6078"
  white: "#B8C0E0"
  yellow: "#EED49F"
  closer: p:os
  lavender: "#B7BDF8"
  os: "#ACB0BE"
  pink: "#F5BDE6"
transient_prompt:
  background: transparent
  foreground: p:pink
  template: "{{ .Segments.Time.CurrentDate | date .Segments.Time.Format }} {{ if .Root }}#>{{ else }}~>{{end}} "
